### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dgslos** [amkozlov/sativa#2]
Since Python 2 is end of life, it would be great to see Python 3 support for SATIVA.

**Comment by amkozlov** [comment]
@dgslos  I just moved SATIVA to Python 3, please feel free to test!

**Comment by dgslos** [comment]
@amkozlov, I can confirm sativa is running with Python 3. I just tested it inside a docker. Thanks for moving it to Python 3!

**Comment by amkozlov** [comment]
@dgslos perfect, thanks for confirmation!

**Comment by dgslos** [comment]
I was a bit too fast 
![image](https://user-images.githubusercontent.com/65173064/107394558-4e20b000-6afc-11eb-9b09-8530b123e67e.png)

**Comment by amkozlov** [comment]
please try to replace this line
 
https://github.com/amkozlov/sativa/blob/master/sativa.py#L366

with
```
 rank_parent, rank_tips = self.get_parent_tip_ranks(self.tax_tree)
```

**Comment by dgslos** [comment]
I did that. Now it can't find an attribute 
![image](https://user-images.githubusercontent.com/65173064/107488534-c41e2900-6b87-11eb-93d5-53b9dad7f623.png)

I don't see a method defined with that name in the class. My python is not could enough to understand classes fully.

**Comment by amkozlov** [comment]
Sorry, apparently you are using `-ranktest` option which I haven't tested after Python 3 conversion. It should be fixed now, please check.

**Comment by amkozlov** [comment]
I assume this is now fixed. Otherwise, please reopen.
