### ISSUE TITLE
Issue with raxml

### ISSUE THREAD

**Issue by jendawkins** [amkozlov/sativa#3]
I got the error: "RAxML run failed (mutlifurcation resolution)" and, in the log file, "run_raxml.sh failed with: Could not find working RAxML binary."

I'm assuming there are some package version issues or something causing RAxML to fail -- any suggestions on how to fix this? 

Thanks!

**Comment by amkozlov** [comment]
Did you run the installation script `install.sh`?

If so, please post full output/log files.

**Comment by amkozlov** [comment]
I assume this was fixed. Otherwise, please reopen and post your log file.
