### ISSUE TITLE
Installation failing on Ubuntu 22.04

### ISSUE THREAD

**Issue by dgslos** [amkozlov/sativa#6]
The if statement checking for gcc version >4.6 or >4.7 is not working anymore since we are version 11 now. This can be fixed with adding ||  (( $(echo "$GCC_VERSION > 9" |bc -l) )) but I'm getting more errors:

![image](https://github.com/amkozlov/sativa/assets/65173064/9075a08f-4799-44dc-8335-53e24ee9a1a2)

Is there a way to resolve this with docker for the moment until this is fixed?

Thanks!

**Comment by amkozlov** [comment]
this should be fixed now, please check!

**Comment by dgslos** [comment]
That fixed it! Thanks :)
